### ISSUE TITLE
parser less 

### ISSUE THREAD

**Issue by MagicLinuxRing** [nicklockwood/XMLDictionary#56]
I have xml string like this,in the group node ,the key cann't be parsed,because it contain '&'.
how can i solve it?
\<key\>Qo5n0tSUYBUFBJ1ttCk3ffMXa6E51__iFrBIeQ..&q=bj0xJmE8mJgYmC\<\/key\>

**Comment by MagicLinuxRing** [comment]
<key>Qo5n0tSUYBUFBJ1ttCk3ffMXa6E51__iFrBIeQ..&q=bj0xJmE8mJgYmC</key>

like this..

**Comment by nicklockwood** [comment]
This is invalid XML, since `&` must be encoded as `&amp;` to be compliant with the XML spec.

XMLDictionary uses Apple's NSXMLParser, so I can't force it to accept invalid XML. If you can't fix the XML source, the only option you have is to pre-process the XML data by converting it to a string and using regex to replace "&" with "&amp;" before passing it to XMLDictionary.

**Comment by MagicLinuxRing** [comment]
thanks! my xml surely has error!
